---
title: Cincopa
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@cincopa.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
tagline: Global Investment Boutique
Phone: "+972-3710-4000"
Address: |-
  Millennium Tower
  17 HaArba'a Street
  Tel Aviv 64739
  Israel
Fax: "+972-3710-4027"
